# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: cargo build it
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          use-cross: true
          args: --no-default-features --release --target wasm32-unknown-unknown
      - name: install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.1.0
      - name: run wasm-bindgen
        run: wasm-bindgen --out-dir ./out/ --target web --weak-refs --reference-types ./target/wasm32-unknown-unknown/release/mapbuilder.wasm
      - name: create web folder
        run: mkdir web && cp index.html web && cp script.js web && cp -r out web && cp -r assets web
      - name: publish to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          target_branch: gh-pages
          publish_dir: ${{github.workspace}}/web
          github_token: ${{ secrets.GITHUB_TOKEN }}
